### ISSUE TITLE
Create simple bootstrap.sh

### ISSUE THREAD

**Issue by overholt** [Mozilla-TWQA/Hasal#199] opened 2016-08-16 15:36 UTC
Something like Eideticker's would be nice: https://github.com/mozilla/eideticker/blob/master/bootstrap.sh. We can even set it up with Travis like Eideticker has so that it's guaranteed to always work :)

**Comment by ShakoHo** [comment] 2016-08-18 07:54
maybe we can modify the install_hasal.sh to fulfill this?
@askeing  how do you think?

**Comment by askeing** [comment] 2016-08-18 09:30
I think it should works, but it may meet some problem.
* `apt-get` will takes the long time
* building `opencv` also have to wait the long time
* `setup sikulix` will have problem, have to skip it on Travis

Ref: https://docs.travis-ci.com/user/customizing-the-build/#Build-Timeouts

**Comment by overholt** [comment] 2016-08-18 14:58
We could perhaps skirt the timeout issue if we used a pre-build OpenCV (https://github.com/Mozilla-TWQA/Hasal/issues/198).

For sikulix, could we make our own .deb repo or just manually extract the JAR file(s)?

**Comment by askeing** [comment] 2016-08-23 03:30
@ypwalter , you are more familiar with sikulix, do you have any idea?

**Comment by askeing** [comment] 2016-09-02 09:52
Currently working on the Mac bootstrap.
It will also run on Travis CI for verifying it works fine.

**Comment by digitarald** [comment] 2016-10-28 22:42
From what I can tell the issue is fixed, could this be closed?

**Comment by ShakoHo** [comment] 2016-11-01 02:24
Yes, we should close this one.

**Closed by ShakoHo** 2016-11-01 02:24 UTC
